### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ghost** [nicholaskajoh/jack#1]
Have you gotten the SSL termination set-up with LE? If so, could you expand a little on how to accomplish that in [your blog post](https://medium.com/@nicholaskajoh/how-to-run-multiple-apps-on-one-server-using-docker-and-traefik-de3f6a5ddb4c)? The [traefik docs](https://docs.traefik.io/user-guide/docker-and-lets-encrypt/) seem to indicate automagic but don't currently take the user from start to finish.

**Comment by nicholaskajoh** [comment]
Hi @jhabdas were you able to figure it out?

**Comment by ghost** [comment]
Indeed. Thanks again!
